version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_notification
    environment:
      POSTGRES_DB: notification-db
      POSTGRES_USER: leozinho
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
