spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce

kafka:
  url: localhost:9092
  topic: notification-topic
  group: notification-group
server:
  port: 8081