spring:


  datasource:
    url: jdbc:postgresql://localhost:5433/notification-db
    username: leozinho
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true;

  flyway:
    enabled: true